# Generated by Django 5.1.1 on 2025-01-29 12:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video_link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видеоинструкция')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
        migrations.CreateModel(
            name='ExerciseTrainingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Таймер')),
                ('target_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Планируемый вес')),
                ('target_reps', models.IntegerField(blank=True, null=True, verbose_name='Планируемое кол-во повторений')),
                ('target_sets', models.IntegerField(blank=True, null=True, verbose_name='Планируемое кол-во подходов')),
                ('general_order', models.IntegerField(blank=True, null=True, verbose_name='Порядковый номер')),
                ('is_done', models.BooleanField(default=False, verbose_name='Статус выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий тренера')),
                ('client_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий клиента')),
                ('best_result', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Лучший результат')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_in_workouts', to='workout.exercise', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Упражнение и блок',
                'verbose_name_plural': 'Упражнения и блоки',
            },
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Планируемый вес')),
                ('terget_reps', models.IntegerField(blank=True, null=True, verbose_name='Планируемое кол-во повторений')),
                ('actual_weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Фактический вес')),
                ('actual_reps', models.IntegerField(blank=True, verbose_name='Фактическое кол-во повторений')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_last', models.BooleanField(default=False, verbose_name='Заключетельный подход')),
                ('excercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='workout.exercisetrainingsegment')),
            ],
            options={
                'verbose_name': 'Подход',
                'verbose_name_plural': 'Подходы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг Тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'constraints': [models.UniqueConstraint(fields=('name', 'slug'), name='unique_tag')],
            },
        ),
        migrations.CreateModel(
            name='TagExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.exercise', verbose_name='Упражнение')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Упражнение и тэг',
                'verbose_name_plural': 'Упражнения и тэги',
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='tags',
            field=models.ManyToManyField(related_name='exercises', through='workout.TagExercise', to='workout.tag', verbose_name='Тэг упражнения'),
        ),
        migrations.CreateModel(
            name='TagWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тренировка и тэг',
                'verbose_name_plural': 'Тренировки и тэги',
            },
        ),
        migrations.CreateModel(
            name='TrainingSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Таймер')),
                ('is_circle', models.BooleanField(default=False, verbose_name='Круговая')),
                ('number_laps', models.IntegerField(default=1, verbose_name='Количество кругов')),
                ('exercises', models.ManyToManyField(related_name='training_segment', through='workout.ExerciseTrainingSegment', to='workout.exercise', verbose_name='Упражнения в блоке')),
            ],
            options={
                'verbose_name': 'Тренировочный блок',
                'verbose_name_plural': 'Тренировочные блоки',
            },
        ),
        migrations.AddField(
            model_name='exercisetrainingsegment',
            name='training_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exercises', to='workout.trainingsegment', verbose_name='Блок упражнений'),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата тренировки')),
                ('timing', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Таймер')),
                ('tags', models.ManyToManyField(related_name='workouts', through='workout.TagWorkout', to='workout.tag', verbose_name='Тэги тренировки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
            },
        ),
        migrations.AddField(
            model_name='trainingsegment',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_segments', to='workout.workout', verbose_name='Тренировка'),
        ),
        migrations.AddField(
            model_name='tagworkout',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout', verbose_name='Тренировка'),
        ),
        migrations.AddConstraint(
            model_name='tagexercise',
            constraint=models.UniqueConstraint(fields=('tag', 'exercise'), name='unique_exercise_tag'),
        ),
        migrations.AddConstraint(
            model_name='exercisetrainingsegment',
            constraint=models.UniqueConstraint(fields=('training_segment', 'exercise'), name='unique_exercise_training_segment'),
        ),
        migrations.AddConstraint(
            model_name='tagworkout',
            constraint=models.UniqueConstraint(fields=('tag', 'workout'), name='unique_workout_tag'),
        ),
    ]
