# Generated by Django 5.1.1 on 2025-03-16 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisetrainingsegment',
            name='unique_exercise_training_segment',
        ),
    ]
