# Generated by Django 5.1.1 on 2025-03-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_remove_exercisetrainingsegment_unique_exercise_training_segment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='excercise',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='terget_reps',
            new_name='target_reps',
        ),
        migrations.AddConstraint(
            model_name='exercisetrainingsegment',
            constraint=models.UniqueConstraint(fields=('training_segment', 'exercise'), name='unique_exercise_training_segment'),
        ),
    ]
