# Generated by Django 5.1.1 on 2025-03-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_rename_excercise_set_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercisetrainingsegment',
            name='unique_exercise_training_segment',
        ),
    ]
