version: '3.3'
services:

    mini_app:
        build:
            context: ../mini-app
            dockerfile: Dockerfile
        ports:
        - "3000:3000"
        volumes:
            - ../mini-app:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - web

    web:
        build:
            context: ../backend
            dockerfile: Dockerfile
        # command: python manage.py runserver 0.0.0.0:8000
        environment:
            - DJANGO_SETTINGS_MODULE=assistant.settings
        restart: always
        volumes:
            - static_volume:/app/
        ports:
            - "8000:8000"
        env_file:
            ./.env.dev

    nginx:
        image: nginx:1.19.3
        ports:
        - "80:80"
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - ../mini-app/build:/usr/share/nginx/html/
        - static_volume:/var/html/static/
        - media_volume:/var/html/media/
        depends_on:
            - web
            - mini_app



volumes:
    static_volume:
    media_volume: